language: c++

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-5


before_script:
  - CC=gcc-5
  - CXX=g++-5

script: 
  - ./install.sh
  - python tests/run_tests.py

branches:
    only:
    - master
