sudo: required
cache: apt
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env:
      - CC=g++-6
      - CXX=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - pandoc
          - mpich
    - os: osx
      osx_image: xcode9.2


before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT



script: 
  - ./install.sh
  - python tests/run_unittests.py
  - python tests/run_generax_tests.py

