sudo: required
cache: apt
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: 
      - CC=G++-6
      - CXX=G++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - pandoc
          - mpich
      env : MPI_IMPL=mpich
    - os: osx
      osx_image: xcode9.2
      env: MPI_IMPL=mpich


before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT

install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL


script: 
  - ./install.sh
  - python tests/run_unittests.py
  - python tests/run_generax_tests.py

