language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      before_script: CC=gcc-5 && CXX=g++-5
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-5
      - clang
      - mpich2 
      - mpich2-doc
      - libmpich-dev
      - python


script: 
  - ./install.sh
  - python tests/run_generax_tests.py

