sudo: required
cache: apt
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - pandoc
          - mpich
          - libmpich-dev
    - os: linux
      dist: trusty
      env: CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - pandoc
    - os: osx
      osx_image: xcode9.2

before_install:
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew update; brew install mpich        ; fi
  

script: 
  - ./install.sh
  - python tests/run_unittests.py
  - python tests/run_generax_tests.py

